command_timeout = 1000

[line_break]
disabled = true

[package]
disabled = true

[hostname]
ssh_only = false
format =  "[$hostname](bold red) "
disabled = true

[username]
style_user = "blue bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[sudo]
style = 'bold green'
symbol = '💻'
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]
min_time = 60_0000

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false

[gcloud]
disabled = true

[jobs]
disabled = true
