command_timeout = 1000


[directory]
style = "blue bold"

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = false
format = ":[$hostname]($style) "

[aws]
disabled = true

[docker_context]
disabled = true

